/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppDashboardsRouteImport } from './routes/_app.dashboards'
import { Route as AppGrantsRouteImport } from './routes/_app.grants'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppOpportunitiesRouteImport } from './routes/_app.opportunities'
import { Route as AppOrganisationsRouteImport } from './routes/_app.organisations'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppAdminSlugRouteImport } from './routes/_app.admin.$slug'
import { Route as AppAdminNotificationsRouteImport } from './routes/_app.admin.notifications'
import { Route as AppAdminPeopleRouteImport } from './routes/_app.admin.people'
import { Route as AppAdminTeamRouteImport } from './routes/_app.admin.team'
import { Route as AppGrantsIndexRouteImport } from './routes/_app.grants.index'
import { Route as AppGrantsIdRouteImport } from './routes/_app.grants.$id'
import { Route as AppOpportunitiesIndexRouteImport } from './routes/_app.opportunities.index'
import { Route as AppOpportunitiesIdRouteImport } from './routes/_app.opportunities.$id'
import { Route as AppOrganisationsIndexRouteImport } from './routes/_app.organisations.index'
import { Route as AppOrganisationsIdRouteImport } from './routes/_app.organisations.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardsRoute = AppDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AppRoute,
} as any)
const AppGrantsRoute = AppGrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganisationsRoute = AppOrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSlugRoute = AppAdminSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminNotificationsRoute = AppAdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPeopleRoute = AppAdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTeamRoute = AppAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppGrantsIndexRoute = AppGrantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGrantsRoute,
} as any)
const AppGrantsIdRoute = AppGrantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppGrantsRoute,
} as any)
const AppOpportunitiesIndexRoute = AppOpportunitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOpportunitiesRoute,
} as any)
const AppOpportunitiesIdRoute = AppOpportunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOpportunitiesRoute,
} as any)
const AppOrganisationsIndexRoute = AppOrganisationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrganisationsRoute,
} as any)
const AppOrganisationsIdRoute = AppOrganisationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOrganisationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/contacts': typeof AppContactsRoute
  '/dashboards': typeof AppDashboardsRoute
  '/grants': typeof AppGrantsRouteWithChildren
  '/leads': typeof AppLeadsRoute
  '/opportunities': typeof AppOpportunitiesRouteWithChildren
  '/organisations': typeof AppOrganisationsRouteWithChildren
  '/admin/$slug': typeof AppAdminSlugRoute
  '/admin/notifications': typeof AppAdminNotificationsRoute
  '/admin/people': typeof AppAdminPeopleRoute
  '/admin/team': typeof AppAdminTeamRoute
  '/grants/$id': typeof AppGrantsIdRoute
  '/opportunities/$id': typeof AppOpportunitiesIdRoute
  '/organisations/$id': typeof AppOrganisationsIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/grants/': typeof AppGrantsIndexRoute
  '/opportunities/': typeof AppOpportunitiesIndexRoute
  '/organisations/': typeof AppOrganisationsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/contacts': typeof AppContactsRoute
  '/dashboards': typeof AppDashboardsRoute
  '/leads': typeof AppLeadsRoute
  '/': typeof AppIndexRoute
  '/admin/$slug': typeof AppAdminSlugRoute
  '/admin/notifications': typeof AppAdminNotificationsRoute
  '/admin/people': typeof AppAdminPeopleRoute
  '/admin/team': typeof AppAdminTeamRoute
  '/grants/$id': typeof AppGrantsIdRoute
  '/opportunities/$id': typeof AppOpportunitiesIdRoute
  '/organisations/$id': typeof AppOrganisationsIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/grants': typeof AppGrantsIndexRoute
  '/opportunities': typeof AppOpportunitiesIndexRoute
  '/organisations': typeof AppOrganisationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/contacts': typeof AppContactsRoute
  '/_app/dashboards': typeof AppDashboardsRoute
  '/_app/grants': typeof AppGrantsRouteWithChildren
  '/_app/leads': typeof AppLeadsRoute
  '/_app/opportunities': typeof AppOpportunitiesRouteWithChildren
  '/_app/organisations': typeof AppOrganisationsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/admin/$slug': typeof AppAdminSlugRoute
  '/_app/admin/notifications': typeof AppAdminNotificationsRoute
  '/_app/admin/people': typeof AppAdminPeopleRoute
  '/_app/admin/team': typeof AppAdminTeamRoute
  '/_app/grants/$id': typeof AppGrantsIdRoute
  '/_app/opportunities/$id': typeof AppOpportunitiesIdRoute
  '/_app/organisations/$id': typeof AppOrganisationsIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/grants/': typeof AppGrantsIndexRoute
  '/_app/opportunities/': typeof AppOpportunitiesIndexRoute
  '/_app/organisations/': typeof AppOrganisationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/contacts'
    | '/dashboards'
    | '/grants'
    | '/leads'
    | '/opportunities'
    | '/organisations'
    | '/admin/$slug'
    | '/admin/notifications'
    | '/admin/people'
    | '/admin/team'
    | '/grants/$id'
    | '/opportunities/$id'
    | '/organisations/$id'
    | '/admin/'
    | '/grants/'
    | '/opportunities/'
    | '/organisations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/contacts'
    | '/dashboards'
    | '/leads'
    | '/'
    | '/admin/$slug'
    | '/admin/notifications'
    | '/admin/people'
    | '/admin/team'
    | '/grants/$id'
    | '/opportunities/$id'
    | '/organisations/$id'
    | '/admin'
    | '/grants'
    | '/opportunities'
    | '/organisations'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/contacts'
    | '/_app/dashboards'
    | '/_app/grants'
    | '/_app/leads'
    | '/_app/opportunities'
    | '/_app/organisations'
    | '/_app/'
    | '/_app/admin/$slug'
    | '/_app/admin/notifications'
    | '/_app/admin/people'
    | '/_app/admin/team'
    | '/_app/grants/$id'
    | '/_app/opportunities/$id'
    | '/_app/organisations/$id'
    | '/_app/admin/'
    | '/_app/grants/'
    | '/_app/opportunities/'
    | '/_app/organisations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards': {
      id: '/_app/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AppDashboardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grants': {
      id: '/_app/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof AppGrantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities': {
      id: '/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organisations': {
      id: '/_app/organisations'
      path: '/organisations'
      fullPath: '/organisations'
      preLoaderRoute: typeof AppOrganisationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/$slug': {
      id: '/_app/admin/$slug'
      path: '/$slug'
      fullPath: '/admin/$slug'
      preLoaderRoute: typeof AppAdminSlugRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/notifications': {
      id: '/_app/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AppAdminNotificationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/people': {
      id: '/_app/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AppAdminPeopleRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/team': {
      id: '/_app/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AppAdminTeamRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/grants/': {
      id: '/_app/grants/'
      path: '/'
      fullPath: '/grants/'
      preLoaderRoute: typeof AppGrantsIndexRouteImport
      parentRoute: typeof AppGrantsRoute
    }
    '/_app/grants/$id': {
      id: '/_app/grants/$id'
      path: '/$id'
      fullPath: '/grants/$id'
      preLoaderRoute: typeof AppGrantsIdRouteImport
      parentRoute: typeof AppGrantsRoute
    }
    '/_app/opportunities/': {
      id: '/_app/opportunities/'
      path: '/'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof AppOpportunitiesIndexRouteImport
      parentRoute: typeof AppOpportunitiesRoute
    }
    '/_app/opportunities/$id': {
      id: '/_app/opportunities/$id'
      path: '/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof AppOpportunitiesIdRouteImport
      parentRoute: typeof AppOpportunitiesRoute
    }
    '/_app/organisations/': {
      id: '/_app/organisations/'
      path: '/'
      fullPath: '/organisations/'
      preLoaderRoute: typeof AppOrganisationsIndexRouteImport
      parentRoute: typeof AppOrganisationsRoute
    }
    '/_app/organisations/$id': {
      id: '/_app/organisations/$id'
      path: '/$id'
      fullPath: '/organisations/$id'
      preLoaderRoute: typeof AppOrganisationsIdRouteImport
      parentRoute: typeof AppOrganisationsRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminSlugRoute: typeof AppAdminSlugRoute
  AppAdminNotificationsRoute: typeof AppAdminNotificationsRoute
  AppAdminPeopleRoute: typeof AppAdminPeopleRoute
  AppAdminTeamRoute: typeof AppAdminTeamRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminSlugRoute: AppAdminSlugRoute,
  AppAdminNotificationsRoute: AppAdminNotificationsRoute,
  AppAdminPeopleRoute: AppAdminPeopleRoute,
  AppAdminTeamRoute: AppAdminTeamRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppGrantsRouteChildren {
  AppGrantsIdRoute: typeof AppGrantsIdRoute
  AppGrantsIndexRoute: typeof AppGrantsIndexRoute
}

const AppGrantsRouteChildren: AppGrantsRouteChildren = {
  AppGrantsIdRoute: AppGrantsIdRoute,
  AppGrantsIndexRoute: AppGrantsIndexRoute,
}

const AppGrantsRouteWithChildren = AppGrantsRoute._addFileChildren(
  AppGrantsRouteChildren,
)

interface AppOpportunitiesRouteChildren {
  AppOpportunitiesIdRoute: typeof AppOpportunitiesIdRoute
  AppOpportunitiesIndexRoute: typeof AppOpportunitiesIndexRoute
}

const AppOpportunitiesRouteChildren: AppOpportunitiesRouteChildren = {
  AppOpportunitiesIdRoute: AppOpportunitiesIdRoute,
  AppOpportunitiesIndexRoute: AppOpportunitiesIndexRoute,
}

const AppOpportunitiesRouteWithChildren =
  AppOpportunitiesRoute._addFileChildren(AppOpportunitiesRouteChildren)

interface AppOrganisationsRouteChildren {
  AppOrganisationsIdRoute: typeof AppOrganisationsIdRoute
  AppOrganisationsIndexRoute: typeof AppOrganisationsIndexRoute
}

const AppOrganisationsRouteChildren: AppOrganisationsRouteChildren = {
  AppOrganisationsIdRoute: AppOrganisationsIdRoute,
  AppOrganisationsIndexRoute: AppOrganisationsIndexRoute,
}

const AppOrganisationsRouteWithChildren =
  AppOrganisationsRoute._addFileChildren(AppOrganisationsRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppContactsRoute: typeof AppContactsRoute
  AppDashboardsRoute: typeof AppDashboardsRoute
  AppGrantsRoute: typeof AppGrantsRouteWithChildren
  AppLeadsRoute: typeof AppLeadsRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRouteWithChildren
  AppOrganisationsRoute: typeof AppOrganisationsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppContactsRoute: AppContactsRoute,
  AppDashboardsRoute: AppDashboardsRoute,
  AppGrantsRoute: AppGrantsRouteWithChildren,
  AppLeadsRoute: AppLeadsRoute,
  AppOpportunitiesRoute: AppOpportunitiesRouteWithChildren,
  AppOrganisationsRoute: AppOrganisationsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
